# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# Add or remove your plugins here:

[[plugins]]
repo = 'Shougo/denite.nvim'

# 補完関連
[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'ujihisa/neco-look'
#-----

# 開発環境関連
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'preservim/tagbar'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-scripts/surround.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-scripts/Markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'cespare/vim-toml'
